name: Deploy BQML
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/135217867785/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'zta-bioauth-app@forward-sentry-456317-k6.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: 'forward-sentry-456317-k6'

      - name: Execute BQML Training
        run: |
          bq query --use_legacy_sql=false < sql/train_model.sql
